name: Release

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*.*.*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: ethereum/go-ethereum
          path: go-ethereum
          ref: v1.9.24
      - run: git fetch --prune --unshallow
      - name: Setup release environment
        run: |-
          echo 'GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}' > .release-env
          echo 'HOMEBREW_TAP_PAT=${{ secrets.HOMEBREW_TAP_PAT }}' >> .release-env
      - name: Release dry run
        run: make release-dry-run
      - name: Release publish
        run: make release
